export default [
  { value: 'LineChartOutlined' },
  { value: 'SlidersOutlined' },
  { value: 'AppstoreOutlined' },
  { value: 'AppstoreAddOutlined' },
  { value: 'AlertOutlined' },
  { value: 'ApartmentOutlined' },
  { value: 'BarsOutlined' },
  { value: 'BranchesOutlined' },
  { value: 'CalendarOutlined' },
  { value: 'DashboardOutlined' },
  { value: 'DatabaseOutlined' },
  { value: 'DesktopOutlined' },
  { value: 'FileOutlined' },
  { value: 'FileDoneOutlined' },
  { value: 'GlobalOutlined' },
  { value: 'GoldOutlined' },
  { value: 'HomeOutlined' },
  { value: 'MailOutlined' },
  { value: 'MenuOutlined' },
  { value: 'ReadOutlined' },
  { value: 'SolutionOutlined' },
  { value: 'UserOutlined' },
  { value: 'UserSwitchOutlined' },
  { value: 'TeamOutlined' },
  { value: 'SettingOutlined' },
]
